const debug = require('debug')('chinese_whispers:service')
const config = require('./config')
const _options = require('./_options')

require('seneca')({tag: 'chinese_whispers', log: 'silent', timeout: 10000})
    .ready(err => debug('seneca.ready() err:', err))
    .use('./lib/plugins/liar', {provider: 'yandex', lie: `It's YUGE!`})
    .use('./lib/plugins/google')
    .use('./lib/plugins/yandex', {key: config.YANDEX_TRANSLATE_API_KEY})
    .use('./lib/plugins/translator')
    .use('./lib/plugins/conductor')
    .use('mesh', _options(config))
